### ISSUE TITLE
Flagging Issue

### ISSUE THREAD

**Issue by LadyJuse** [adamstark/Gist#12]
So I am using Kiss_FFT, and I have the -DUSE_KISS_FFT flag up. However, when compiling, the AccelerateFFT files are still being compiled. This is causing 84 errors, all from the acceleratefft files.

**Comment by adamstark** [comment]
Hey, do you have both flags enabled perhaps? If the AccelerateFFT flag isn't there the code won't be compiled.

**Comment by LadyJuse** [comment]
I only put the flag up for Kiss_FFT, and the code is saying only KISS_FFT has it's flag up. This is a sample of the code showing that.
![Capture101](https://user-images.githubusercontent.com/33072410/76691417-c12d5800-6607-11ea-96dc-963cce302003.PNG)

**Comment by adamstark** [comment]
You are on Visual Studio on Windows, am I correct? :)

If so, the AccelerateFFT files won't be relevant as they reference an Apple library. I would try deleting the AccelerateFFT files (.h/.cpp) from your Visual Studio project. Let me know if that helps!

**Comment by adamstark** [comment]
(also, apologies that I'm not more on top of the Windows support - it is an ambition of mine to make it better, but I am rarely on a Windows machine so it's hard to test)

**Comment by LadyJuse** [comment]
It's okay, deleting them just causes more errors since the code can't be found. Should I also delete the flagged code in Gist.cpp as well?

**Comment by adamstark** [comment]
It shouldn't have any reference to the headers because of the flag - but you can safely delete any reference to the AccelereateFFT header and hopefully that will help :)

**Comment by LadyJuse** [comment]
Thank you

**Comment by LadyJuse** [comment]
Okay, I think I was overthinking it, I have no errors for Accelerate, but I have unresolved externals for KISS_FFTW
