### ISSUE TITLE
mel-spectrograms

### ISSUE THREAD

**Issue by hannabonert** [adamstark/Gist#19]
Hello,
Thanks for this great library!

Is there any way to use your code to create mel-spectrograms, besides for  dividing the audio into segments of the desired window length, getting the mel-spectrum for each, and putting them together into a mel-spectrogram yourself?

Thank you very much!

**Comment by adamstark** [comment]
Hi there, i think you could get the mel spectrum on each frame, and then put the resulting vector into a vector of vectors. Does that make sense? Let me know if not and i can try and do an example...

**Comment by hannabonert** [comment]
That makes sense.
Thanks!

**Comment by adamstark** [comment]
Great, good luck! :)
