### ISSUE TITLE
Option to get esitmated Onset position

### ISSUE THREAD

**Issue by TheOnlyJoey** [adamstark/Gist#21]
Ohai!

Been enjoying the use of Gist for a bit now, but It seems that the onset detection is missing the most crucial part of Onset detection for me, which is the exact position of the estimated onset.
It seems that the functions only reports back the value when a Onset is detected, not the actual position of the sample in the provided buffer.
Am I missing something? Or is this just not implemented.

Thanks!

**Comment by adamstark** [comment]
Hey, so this is kind of a complicated question - onset detection functions are calculated on a frame-by-frame basis. We could add a peak-picking algorithm that would decide when an onset had occurred, but in practice, this will depend on a few other factors, especially your audio frame size. So it won't come back with a sample in the buffer where the onset has occurred - I have provided these functions so you can define how you want to detect onsets. I'll consider some kind of onset detection algorithm (I have a few written already) but I'd need to think about something that works across all use-cases...

**Comment by victorpalle** [comment]
Hello !

I'm new to audio manipulation and I'd like to know how to use properly your gists function to do onset detection. First question is I don't know what to put in the energyDifference function paramaters. Can you explain me a little bit ?
Thank you ;)
