### ISSUE TITLE
Gist is not working!

### ISSUE THREAD

**Issue by RodneyYourAreGoodAtThis** [adamstark/Gist#22]
First, thank you for both AudioFile and Gist. AudioFile has been working well but I cannot make any progress with Gist. I am receiving this error:
C:\Users\nabee\AppData\Local\Temp\ccUdNSDs.o: In function `Z30loadAudioFileAndProcessSamplesv':
C:/Users/nabee/Senior Project/AudioFile Gist/music.cpp:73: undefined reference to `Gist<float>::Gist(int, int, WindowType)'
C:/Users/nabee/Senior Project/AudioFile Gist/music.cpp:98: undefined reference to `Gist<float>::processAudioFrame(std::vector<float, std::allocator<float> > const&)'
C:/Users/nabee/Senior Project/AudioFile Gist/music.cpp:101: undefined reference to `Gist<float>::highFrequencyContent()'
C:/Users/nabee/Senior Project/AudioFile Gist/music.cpp:73: undefined reference to `Gist<float>::~Gist()'
C:/Users/nabee/Senior Project/AudioFile Gist/music.cpp:73: undefined reference to `Gist<float>::~Gist()'
collect2.exe: error: ld returned 1 exit status

I have added <cstdlib> and have a direct path to MFCC.h but am still receiving the error. Please help.

**Comment by adamstark** [comment]
Hi there, it looks like you are not including the .cpp files in your project. Without them the header files only define the functions that can be called, but you need to include the .cpp files so that your code has access to the definition / implementation of the Gist library

**Comment by RodneyYourAreGoodAtThis** [comment]
Thank you for responding. 
I have coupled all the header files with their .cpp counterparts. The errors are all gone. Thank you very much and have a happy new year.

**Comment by adamstark** [comment]
Glad to hear that :) Happy new year to you too !

**Comment by RodneyYourAreGoodAtThis** [comment]
Hello again,
My idea, in choosing your work, was to sample a wave file, and run the samples through Gist(fft) to obtain the values in the frequency domain. With my knowledge on Fourier transforms, you should be able to obtain the keys or harmonies contained in the original file. I am failing in this.
I have obtained the samples via AudioFile->Created a Gist object with the number of samples as the frame size -> gist.processAudioFrame(v); -> Mel-frequency Spectrum is all zeroes -> FFT Magnitude Spectrum is all zeroes -> MFCCs has barely any info I can use. Am I doing this wrong? I was expecting a vector to which I could compare the known frequencies of music notes.
Please advise.

**Comment by adamstark** [comment]
I believe you haven't setup the FFT correctly - you will need to include one of the options for FFTs. Have a look at the Dependencies section of the README: https://github.com/adamstark/Gist#dependencies

**Comment by RodneyYourAreGoodAtThis** [comment]
Thank you for all your help.
Unfortunately, I cannot keep using your work. My advisor has informed me that my idea is too ambitious and can only be achieved at a graduate level and not as an undergrad. It seems i did not take into account that the fast Fourier transforms only tell me that the frequencies are present but not how many and when they occur. Modifying the code to achieve this would take too much time away from my senior project. Thank you so much and all the best.

**Comment by adamstark** [comment]
Ok, sorry to hear that - best of luck with your work.
