### ISSUE TITLE
Chunk overlap strategy 

### ISSUE THREAD

**Issue by isgursoy** [adamstark/Gist#24]
Bringing to make discussion https://github.com/adamstark/Gist/issues/13#issuecomment-868965008 visible.

**Comment by adamstark** [comment]
Sorry for the late reply to this. Yes, the chunk overlapping is left to the person using the library. In theory there could be something like this put into the library, but for the most part it gives the flexibility to the consumer of the library to setup their overlap strategy as they wish :)
