### ISSUE TITLE
About how to use FFT 

### ISSUE THREAD

**Issue by yvettemuki** [adamstark/Gist#25]
Hello, I am using the Gist and AudioFile to retrieve FFT data from the input audio file, but forgive me I have no idea to set the flag. Could you explain how to set up the FFT function in Visual Studio Solution project? If I want to use KiSS_FFT, I also need to link the library into my project? Thanks so much if you can reply to me.

**Comment by martinvanaud** [comment]
Im having a similar issue, how can i add the flag -DUSE_FFTW ? 
In your CMakeLists or in the Makefile generated ?

Thank you : )

**Comment by adamstark** [comment]
If you take a look at the `src` directory there is a `CMakeLists.txt` file in there. I believe if you change:

`target_compile_definitions (Gist PUBLIC -DUSE_KISS_FFT)`

to

`target_compile_definitions (Gist PUBLIC -DUSE_FFTW)`

then that should add the flag. You'll need to make sure you have FFTW installed and you might need to find a way to add the linker flag for FFTW also.

Thanks,
Adam

**Comment by yvettemuki** [comment]
I have solved the problem with another method. But anyway, thanks for the reply.
