### ISSUE TITLE
Website down. Any chance to download the compiled plugin VST?

### ISSUE THREAD

**Issue by moebiussurfing** [adamstark/Gist#28]
hello @adamstark ,
it looks that your site is down.
could you share the plugin as a release here on GH?
regards

**Comment by adamstark** [comment]
Hi there, this is a C++ library. Are you referring to the Sound Analyser plugin? 

If so, it has been a while since I did a release of that. I am working (slowly) on a new version and will share that when it is done on the website.

**Comment by moebiussurfing** [comment]
yes, I was looking for Sound Analyzer plugin.
Yesterday, your website was down. Now is working. 
http://adamstark.co.uk/project/gist/

Cool that you are working on a new version. I suppose that would be 64 bits.
macOS only or also Windows?

**Comment by adamstark** [comment]
I'd try and do a cross-platform version if I can. Need to find some time to finish it off :)

**Comment by adamstark** [comment]
And yes, 64-bit
