### ISSUE TITLE
unknown type name 'size_t'; did you mean '__gnu_cxx::size_t'? column: 70, line: 94

### ISSUE THREAD

**Issue by giuliomoro** [adamstark/Gist#5]
When building a file that includes `MFCC.h`.
`size_t` requires an `#include <stddef.h>`,  or you can use `std::size_t` instead.

**Comment by adamstark** [comment]
Ah, ok, thank you. Which platform is this on? I will likely add #include <stddef.h> as an include then

**Comment by giuliomoro** [comment]
I'd suggest `std::size_t` (see my [Pull Request](https://github.com/adamstark/Gist/pull/6)).

That was on Debian Stretch, armv7, using `clang++` 3.9.  Similar error (but less verbose) with `g++` 6.3.

**Comment by adamstark** [comment]
Ok, excellent - I have now updated this on the develop branch. I'm not sure when I'll next be doing a master version, but soon I hope.

**Comment by rhaleblian** [comment]
Hi, this came up in other source files when i was building them on Xenomai/Bela. I used `using namespace std` to resolve it, but that is just a third way to approach it.
