### ISSUE TITLE
Issue compiling using VS2017.

### ISSUE THREAD

**Issue by adamstark** [adamstark/Gist#9]
Issue compiling using VS2017. 

```
template <class T>
void MFCC<T>::discreteCosineTransform (std::vector<T>& inputSignal, const size_t numElements)
{
    // the input signal must have the number of elements specified in the numElements variable
    assert (inputSignal.size() == numElements);

    T signal[numElements]; // copy to work on   --> this is throwing an error 
```

Error   C2131   expression did not evaluate to a constant       Project

**Comment by maxgraf96** [comment]
Is there any progress on that? I'm using VS2019 and it gives me the same error.

**Comment by matthiasseibold** [comment]
`T signal[numElements]; // copy to work on` 

This is a Variable Length Array which is not standard in C++. Some compilers like GCC allow them as an extensions but MSVS will not compile them.

Change it to: 
`T* signal = new T[numElements]; `

solves the issue.

**Comment by Crypto2** [comment]
afaik VS still doesn't support arrays that use a variable to define the size, you'd have to convert it to use new or malloc to make an array.

**Comment by PcChip** [comment]
if I change it to   
`T* signal = new T[numElements]; // copy to work on`  
  
it builds. No idea if it works though.

**Comment by adamstark** [comment]
The problem is that a) that pointer will need deleting or it will leak memory; and b) the memory is allocated on the heap, which is potentially slow. 

Does it work if you replace it with...

`std::array<T,numElements> signal;`

?

You might need to `#include <array>`

I don't have a Windows machine to hand so it'd be great if someone could check :)

**Comment by PcChip** [comment]
regarding Array, it doesn't compile that way  
  
`Error	C2975	'_Size': invalid template argument for 'std::array', expected compile-time constant expression`

**Comment by adamstark** [comment]
Hi @PcChip, @Crypto2, @maxgraf96 - I've just pushed what I think is a fix to the develop branch. I'm not on a Windows machine, could you guys check this solves your problem?

Thanks

**Comment by adamstark** [comment]
This is now on the master branch
